### ISSUE TITLE
mlBundle permissions issue on Windows 10

### ISSUE THREAD

**Issue by sparnell** [marklogic-community/marklogic-unit-test#126] opened 2020-04-07 20:14 UTC
After adding ml-unit-test to my build.gradle file as 
  mlBundle "com.marklogic:marklogic-unit-test-modules:1.0.0"
then running mlDeploy, I end up with files in 
  build/mlBundle/marklogic-unit-test-modules/root/test/img 
which I don't have any permissions on. Since I'm unable to read them, they can't be deleted or overwritten, which means all deployments fail. I'm also not able to change the permissions using a local administrator account.

**Comment by cmatheus** [comment] 2020-04-07 20:17
this kind of issue can arise on Windows machines if virus protection is monitoring your project directory.

**Comment by rjrudin** [comment] 2020-04-07 20:20
Yeah you have to have read/write permission on the "build" directory, as that's Gradle's default directory for compiling Java code, building artifacts, etc. And ml-gradle uses it for extracting bundle zips as well. I think what @cmatheus  said is likely the root cause.

**Comment by sparnell** [comment] 2020-04-07 20:30
This is what I suspected. I'll reach out to the customer's IT support.

**Comment by rjrudin** [comment] 2021-03-09 19:37
Closing, assuming issue is resolved

**Closed by rjrudin** 2021-03-09 19:37 UTC
